### ISSUE TITLE
Question on Scrapy

### ISSUE THREAD

**Issue by Ranybaug** [mjhea0/thinkful-html#4]
HI Michael,

I saw your youtube video on Scrappy  , I have one question regarding how can I save html data which we have crawled preserving all those links as it to mock a site locally ? I mean is it possible using scrapy preserving all navigation links of websites as it is locally (creating directory structure)

**Comment by mjhea0** [comment]
You should not use a scraper / crawler for this. Scrapers are best for grabbing specific data on a site. If you want the *entire* site,  then just download the entire thing with something like http://www.httrack.com/.
